spring.application.name=digital-education-record

server.port = 8080

# datasource (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/digitaleducationrecord
spring.datasource.username=root
spring.datasource.password=radha
# jpa / hibernate
spring.jpa.hibernate.ddl-auto=update
