# example -> application known as application.properties
spring.application.name=crud_operation

#  mongoDB atlas
spring.data.mongodb.uri=mongodb+srv://username:<db_password>@cluster0.hmccjjp.mongodb.net/?appName=Cluster0


# datasource (MySQL)
spring.datasource.url= url of database
spring.datasource.username= root
spring.datasource.password= password
# jpa / hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# thymeleaf
spring.thymeleaf.cache=false

# Exposing 1 endpoint beneath base path '/actuator' with context path '/appis/a1'
server.servlet.context-path = /appis/a1

# oauth2

# google
# step : go to (open)google cloud console  -> (click) API APIs and services ->  (click)Credentials -> (click)on top + CREATE CREDENTIALS  
# ->(SELECT) OAUTH client ID -> if new fill form -> (otherwise) fill another details 4.field(Authorised redirect URIs) =>(http://localhost:8080/login/oauth2/code/google)or Deployed Link.
#  on <> Developer setting


# github
# step : go to (open)github and -> setting -> (scroll) to end -> (click) on <> Developer setting
# -> (click) OAuth Apps -> enter all details in last field (http://localhost:8080/login/oauth2/code/github) then register and get ID and secrets

# spring.security.oauth2.client.registration.google.client-id=${Google_CLIENT_ID}
# spring.security.oauth2.client.registration.google.client-secret=${Google_CLIENT_SECRET}

# spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
# spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}

# Spring default redirect:
# http://localhost:8080/login/oauth2/code/github
# http://localhost:8080/login/oauth2/code/google



# spring security - optional

# spring.security.user.name=admin
# spring.security.user.password=admin
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ----------------MYSQL--------------------
# Property                      =>   Meaning
# spring.datasource.url	        =>  DBC URL of MySQL
# spring.datasource.username	=>  MySQL username
# spring.datasource.password	=>  MySQL password
# spring.jpa.hibernate.ddl-auto	=>  auto-create/update tables
# spring.jpa.show-sql	        =>  prints SQL in console
# hibernate.dialect	            =>  Optimizes SQL for MySQL

# ----------------MongoDB--------------------
# spring.data.mongodb.uri=mongodb://localhost:27017/your_database_name      or(Username + password)
# spring.data.mongodb.uri=mongodb://username:password@localhost:27017/your_database_name


#======== If using both DBs in same project ==================
# ✔ MySQL → JPA
# ✔ MongoDB → MongoRepository
